# Generated by Django 4.2 on 2023-05-01 17:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_remove_playlists_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlists',
            new_name='Playlist',
        ),
    ]
